#!/bin/bash

yorn()
{
	while true; do
		read -p "$* [y/N]: " yn
		case $yn in
			[Yy]*) return 0;;
			[Nn]*) return 1;;
			*) return 0;;
		esac
	done
}

download()
{
	curl --proto '=https' --tlsv1.2 -sSf $1
}

web_install()
{
	name=$1
	url=$2
	args=$3

	script=$(download "$url")
	cand=$(echo "$script" | sha256sum)
	target=$(cat $(dirname $0)/${name}.sha256)
	if [ "${cand}" != "${target}" ]; then
		echo "INVALID SHA256, SKIPPING ${name}"
		echo -e "\tGot '${cand}'"
		echo -e "\tExpected '${target}'"
	fi

	if ! yorn "Install ${name}?"; then
		return 0;
	fi

	if ! sh -c "${script} $3"; then
		echo "Failed installing ${name}"
		return 1;
	fi

	return 0;
}

echo "Bootstrapping yadm"
if yorn "Switch wallpaper? (if using feh)"; then
	mkdir $HOME/.wallpaper
	wget -O $HOME/.wallpaper/wallpaper.jpg https://512pixels.net/downloads/macos-wallpapers-6k/10-10-6k.jpg
fi

if yorn "Installing packaged software (apt/pacman etc)"; then
	# Detect OS version and install corresponding packages


	if grep -q "ID_LIKE=debian" /etc/os-release; then
		echo "Installing Debian packages..."
		sudo apt update
		sudo apt upgrade
		sudo apt install $(cat $HOME/.config/yadm/aptlist)
	elif grep -q "ID_LIKE=arch" /etc/os-release; then
		sudo pacman -Syu $(cat $HOME/.config/yadm/paclist)
	else
		echo "Unsupported OS, skipping"
	fi

	if yorn "Enable ssh-agent?"; then
		sudo systemctl enable --user ssh-agent
	fi
fi

if yorn "Installing non-packaged software"; then
	web_install rust "https://sh.rustup.rs" -y
	web_install nim  "https://nim-lang.org/choosenim/init.sh"
fi

if yorn "Configure user '${USER}' for common user groups"; then
	echo "Setting up user groups, these will require restart to take effect"
	for g in docker dialout wireshark vboxsf; do
		echo "Adding ${USER} to ${g}"
		sudo groupadd "$g" 2>/dev/null
		sudo usermod -aG "$g" ${USER}
	done
fi

sudo ln -sf $HOME/.config/yadm/i3-konsole.sh /etc/profile.d/i3-konsole.sh

if yorn "Swap caps with escape?"; then
	sudo ln -sf $HOME/.config/yadm/swap-caps-esc.sh /etc/profile.d/swap-caps-esc.sh
fi

sudo ln -sf /usr/bin/nvim /usr/bin/vi
echo "Bootstrapping yadm finished"
