#!/bin/bash

yorn()
{
	while true; do
		read -p "$* [y/N]: " yn
		case $yn in
			[Yy]*) return 0;;
			[Nn]*) return 1;;
			*) return 1;;
		esac
	done
}

download()
{
	curl --proto '=https' --tlsv1.2 -sSf $1
}

web_install()
{
	name=$1
	url=$2
	args=$3

	script=$(download "$url")
	cand=$(echo "$script" | sha256sum)
	target=$(cat $(dirname $0)/${name}.sha256)
	if [ "${cand}" != "${target}" ]; then
		echo "INVALID SHA256, SKIPPING ${name}"
		echo -e "\tGot '${cand}'"
		echo -e "\tExpected '${target}'"
	fi

	if ! yorn "Install ${name}?"; then
		return 1;
	fi

	if ! sh -c "${script} $3"; then
		echo "Failed installing ${name}"
		return 1;
	fi

	return 0;
}

echo "Bootstrapping yadm"
if yorn "Installing packaged software (apt/pacman etc)"; then
	# Detect OS version and install corresponding packages
	if egrep -q "ID_LIKE.*debian" /etc/os-release; then
		echo "Installing Debian packages..."
		# Lets install a more modern git...
		sudo add-apt-repository ppa:git-core/ppa
		sudo add-apt-repository ppa:neovim-ppa/stable
		sudo apt update
		sudo apt upgrade
		sudo apt install $(cat $HOME/.config/yadm/aptlist)
	elif egrep -q "ID.*fedora" /etc/os-release; then
		sudo dnf -y group install "C Development Tools and Libraries" "Development Tools" "Sway Desktop"
        sudo dnf update --refresh
        sudo dnf copr enable -y eddsalkield/swaylock-effects
        sudo dnf install --allow-erasing swaylock-effects
		sudo dnf -y install $(cat $HOME/.config/yadm/dnflist)
	else
		echo "Unsupported OS, skipping"
	fi
fi

if yorn "Enable gdb dashboard?"; then
	wget -P ~ https://git.io/.gdbinit -O $HOME/.gdbinit
	pip install pygments
fi

if yorn "Enable powerlevel10k terminal?"; then
    web_install "oh-my-zsh" https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

if yorn "Configure user '${USER}' for common user groups"; then
	echo "Setting up user groups, these will require restart to take effect"
	for g in docker dialout wireshark vboxsf tty tftp; do
		echo "Adding ${USER} to ${g}"
		sudo groupadd "$g" 2>/dev/null
		sudo usermod -aG "$g" ${USER}
	done
fi

if yorn "Unpack etc/ configuration to local machine?"; then
	sudo cp -r $HOME/.config/yadm/root /
fi

echo "Bootstrapping yadm finished"
